version: "3"

services:
  debian_12:
    build:
      context: .
      dockerfile: .docker/Dockerfile-debian_12
    volumes:
      - .:/root/wkhtmltopdf_binary_gem

  amzn_2023:
    build:
      context: .
      dockerfile: .docker/Dockerfile-amzn_2023
    volumes:
      - .:/root/wkhtmltopdf_binary_gem
