FROM --platform=arm64 amazonlinux:2023

RUN dnf update -y && \
    dnf install -y ruby libjpeg-turbo libpng libXrender fontconfig libXext openssl

COPY .docker/lib /lib64/

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
