FROM centos:8
# https://centos.org/centos-stream/#centos-stream-8

# Replace mirror (initial CentOS Linux 8 repos)
RUN find /etc/yum.repos.d -type f -exec sed -i 's/mirrorlist=http:\/\/mirrorlist.centos.org/\#mirrorlist=http:\/\/mirrorlist.centos.org/g' {} \;
RUN find /etc/yum.repos.d -type f -exec sed -i 's/\#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g' {} \;
RUN dnf update -y

# Swap to CentOS Stream 8 repos
RUN dnf swap centos-linux-repos centos-stream-repos -y

# Install centos-release-stream (adds extra repo files, e.g. extras-common)
RUN dnf install centos-release-stream -y
RUN dnf swap centos-{linux,stream}-repos -y

# Re-patch ALL repo files again, since new ones were just added by the steps above
RUN find /etc/yum.repos.d -type f -exec sed -i 's/mirrorlist=http:\/\/mirrorlist.centos.org/\#mirrorlist=http:\/\/mirrorlist.centos.org/g' {} \;
RUN find /etc/yum.repos.d -type f -exec sed -i 's/\#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g' {} \;
RUN dnf update -y

# Sync
RUN dnf distro-sync -y
RUN yum install -y ruby libjpeg-turbo libpng libXrender fontconfig libXext
CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
