FROM centos:8
# CentOS Linux 8 reached EOL Dec 2021; mirrorlist.centos.org is dead.
# Point at vault.centos.org (archived packages) instead of converting to Stream.
RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' *.repo \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' *.repo
RUN dnf update -y
RUN yum install -y ruby libjpeg-turbo libpng libXrender fontconfig libXext
CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
